steps:
# - name: 'python:3.10'
#   entrypoint: 'sh'
#   args:
#     - '-c'
#     - |
#       pip install flake8 &&
#       flake8 --select=E9,F63,F7,F82 .
      
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['compose', '-f', 'docker-compose.test.yml', 'up']
#   env:
#     - DB_USER=root
#     - DB_PASSWORD=rootrm

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--target', 'prod', '-t', '${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/scenes-backstage/microservices.media','--cache-from', '${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/scenes-backstage/microservices.media', '-f', 'media/Dockerfile', '.']

substitutions:
  _LOCATION: us-central1 # default value
  
options:
  logging: CLOUD_LOGGING_ONLY 
  machineType: E2_HIGHCPU_8

images:
# - '${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/scenes-backstage/microservices.auth'
# - '${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/scenes-backstage/microservices.events'
# - '${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/scenes-backstage/microservices.posts'
# - '${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/scenes-backstage/microservices.users'
- '${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/scenes-backstage/microservices.media'