networks:
  default:
    external: true
    name: cloudbuild

services:
  microservices.auth:
    container_name: microservices.auth
    build:
      context: .
      dockerfile: auth/Dockerfile
      target: test
    depends_on:
      - redis
    restart: on-failure
    volumes:
      - ./init/schema.surql:/home/schema.surql
    environment:
      - SCHEMA_FILE=/home/schema.surql

  microservices.media:
    container_name: microservices.media
    build:
      target: test
      context: .
      dockerfile: media/Dockerfile
    depends_on:
      microservices.auth:
        condition: service_completed_successfully
    volumes:
      - ./init/schema.surql:/home/schema.surql

  # microservices.livestream:
  #   container_name: microservices.livestream
  #   build:
  #     target: test
  #     context: .
  #     dockerfile: livestream/Dockerfile
  #   # networks: 
  #   #   - backstage_network
  #   # env_file:
  #   #   - .env
  #   volumes:
  #     - ./init/schema.surql:/home/schema.surql
  #     # - ${GCLOUD_AUTH_DIR}:/root/.config/gcloud:ro
  #   depends_on:
  #     microservices.events:
  #       condition: service_completed_successfully

  microservices.events:
    container_name: microservices.events
    build:
      target: test
      context: .
      dockerfile: events/Dockerfile
    volumes:
      - ./init/schema.surql:/home/schema.surql
    depends_on:
      microservices.auth:
        condition: service_completed_successfully

  microservices.posts:
    container_name: microservices.posts
    build:
      target: test
      context: .
      dockerfile: posts/Dockerfile
    volumes:
      - ./init/schema.surql:/home/schema.surql
    depends_on:
      microservices.events:
        condition: service_completed_successfully

  microservices.users:
    container_name: microservices.users
    build: 
      target: test
      context: .
      dockerfile: users/Dockerfile
    volumes:
      - ./init/schema.surql:/home/schema.surql
    depends_on:
      microservices.posts:
        condition: service_completed_successfully

  redis:
    image: redis
    command: sh -c "redis-server & sleep 60; kill $!"