networks:
  default:
    external: true
    name: cloudbuild

services:
  microservices.auth:
    container_name: microservices.auth
    build:
      context: .
      dockerfile: auth/Dockerfile
      target: prod
    depends_on:
      - redis
    restart: on-failure
    volumes:
      - ./init/schema.surql:/home/schema.surql
    environment:
      - SCHEMA_FILE=/home/schema.surql
    env_file: .env

  microservices.media:
    container_name: microservices.media
    build:
      target: prod
      context: .
      dockerfile: media/Dockerfile
    depends_on:
      microservices.auth:
        condition: service_started
    volumes:
      - ./init/schema.surql:/home/schema.surql
    environment:
      - ENVIRONMENT=dev
    env_file: .env

  # microservices.livestream:
  #   container_name: microservices.livestream
  #   build:
  #     target: prod
  #     context: .
  #     dockerfile: livestream/Dockerfile
  #   volumes:
  #     - ./init/schema.surql:/home/schema.surql
  #   depends_on:
  #     microservices.events:
  #       condition: service_completed_successfully

  microservices.events:
    container_name: microservices.events
    build:
      target: prod
      context: .
      dockerfile: events/Dockerfile
    volumes:
      - ./init/schema.surql:/home/schema.surql
    depends_on:
      microservices.media:
        condition: service_started # service_completed_successfully
    env_file: .env


  microservices.posts:
    container_name: microservices.posts
    build:
      target: prod
      context: .
      dockerfile: posts/Dockerfile
    volumes:
      - ./init/schema.surql:/home/schema.surql
    depends_on:
      microservices.media:
        condition: service_started # service_completed_successfully
    env_file: .env


  microservices.users:
    container_name: microservices.users
    build: 
      target: prod
      context: .
      dockerfile: users/Dockerfile
    volumes:
      - ./init/schema.surql:/home/schema.surql
    depends_on:
      microservices.media:
        condition: service_started # service_completed_successfully
    env_file: .env


  redis:
    image: redis
    command: sh -c "redis-server & sleep 80; kill $!"