networks:
  partyscene_network:
    external: true
    ipam:
      config:
        - subnet: 11.0.0.0/24

services:
  microservices.auth:
    container_name: microservices.auth
    build:
      context: .
      dockerfile: auth/Dockerfile
      target: test
    networks:
      partyscene_network:
        ipv4_address: 11.0.0.14
    restart: always
    depends_on:
      - redis
      - surrealdb
    env_file:
      - .env
    volumes:
      - ./init/schema.surql:/home/schema.surql
    environment:
      - SCHEMA_FILE=/home/schema.surql

  microservices.media:
    container_name: microservices.media
    build: media
    restart: always
    networks:
      partyscene_network:
        ipv4_address: 11.0.0.15
    depends_on:
      - microservices.auth
    env_file:
      - .env
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /root/.config/gcloud/application_default_credentials.json
      GOOGLE_CLOUD_PROJECT: partyscene-441317
      LOCATION: us-central1
    volumes:
      - ${GCLOUD_AUTH_DIR}:/root/.config/gcloud:ro 
      # Change this if not windows 
      - ./shared:/app/shared/

  microservices.livestream:
    container_name: microservices.livestream
    build: livestream
    restart: always
    networks:
      partyscene_network:
        ipv4_address: 11.0.0.13
    env_file:
      - .env
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /root/.config/gcloud/application_default_credentials.json
      GOOGLE_CLOUD_PROJECT: partyscene-441317
      LOCATION: us-central1
      STREAM_TYPE: HLS
      OUTPUT_URI: gs://partyscene-scenes/output
    volumes:
      - ${GCLOUD_AUTH_DIR}:/root/.config/gcloud:ro 
      - ./shared:/app/shared/
    depends_on:
      - microservices.auth

  microservices.events:
    container_name: microservices.events
    build: events
    restart: always
    networks:
      partyscene_network:
        ipv4_address: 11.0.0.12
    env_file:
      - .env
    volumes:
      - ./shared:/app/shared/
    depends_on:
      - microservices.auth

  microservices.posts:
    container_name: microservices.posts
    build: posts
    restart: always
    networks:
      partyscene_network:
        ipv4_address: 11.0.0.11
    env_file:
      - .env
    environment:
      - MEDIA_MICROSERVICE_URL=http://microservices.media:5510/upload
    volumes:
      - ./shared:/app/shared/
    depends_on:
      - microservices.auth

  microservices.users:
    container_name: microservices.users
    build: users
    restart: always
    networks:
      partyscene_network:
        ipv4_address: 11.0.0.10
    env_file:
      - .env
    volumes:
      - ./shared:/app/shared/
    depends_on:
      - microservices.auth

  kong:
    image: kong/kong-gateway:3.8.0.0
    networks:
      partyscene_network:
        ipv4_address: 11.0.0.19
    ports:
      - 8002:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
      - 8005:8002
    volumes:
      - ./kong/declarative:/kong/declarative/
    environment:
      KONG_DATABASE: off
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_GUI_URL: http://localhost:8005
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_DECLARATIVE_CONFIG: ./kong/declarative/kong.yml
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl

  redis:
    image: redis
    # ports:
    #   - 6379:6379  # exposed for only debugging
    volumes:
      - ./data/redis:/data
    networks:
      partyscene_network:
        ipv4_address: 11.0.0.18

  surrealdb:
    env_file:
      - .env
    entrypoint:
      - /surreal
      - start
      - --user
      - $DB_USER
      - --pass
      - $DB_PASSWORD
      - memory

    image: surrealdb/surrealdb:v2.0-dev
    ports:
      - 8000:8000
    networks:
      partyscene_network:
        ipv4_address: 11.0.0.20
    volumes:
      - ./data/database.db:/database.db