version: '3'

services:

  microservices.user:
    container_name: microservices.user
    build: users
    restart: always
    ports:
      - "8080:5510"

  surrealdb:
    env_file:
      - .env
    entrypoint: 
      - /surreal 
      - start
      - --user
      - $DB_USER
      - --pass
      - $DB_PASSWORD
    image: surrealdb/surrealdb:latest
    ports:
      - 8000:8000
    volumes:
      - ./data/database.db:/database.db