apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    autopilot.gke.io/resource-adjustment: '{"input":{"containers":[{"name":"microservices-events-sha256-1"}]},"output":{"containers":[{"limits":{"ephemeral-storage":"1Gi"},"requests":{"cpu":"100m","ephemeral-storage":"1Gi","memory":"128Mi"},"name":"microservices-events-sha256-1"}]},"modified":true}'
    autopilot.gke.io/warden-version: 31.23.0-gke.9
    deployment.kubernetes.io/revision: "166"
  creationTimestamp: "2025-03-07T09:05:40Z"
  generation: 609
  labels:
    app: microserv.events
    app.kubernetes.io/managed-by: cloud-console
  name: microserv.events
  namespace: default
  resourceVersion: "74772903"
  uid: e1032928-a676-4312-b730-6e0db417afd0
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: microserv.events
      app.kubernetes.io/managed-by: cloud-console
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-05-01T03:40:46-05:00"
      creationTimestamp: null
      labels:
        app: microserv.events
        app.kubernetes.io/managed-by: cloud-console
    spec:
      containers:
      - env:
        - name: RABBITMQ_URI
          valueFrom:
            configMapKeyRef:
              key: RABBITMQ_URI
              name: microserv.events-config-y2ek
        - name: RABBITMQ_MEDIA_QUEUE
          valueFrom:
            configMapKeyRef:
              key: RABBITMQ_MEDIA_QUEUE
              name: microserv.events-config-y2ek
        - name: RABBITMQ_R18E_QUEUE
          valueFrom:
            configMapKeyRef:
              key: RABBITMQ_R18E_QUEUE
              name: microserv.events-config-y2ek
        - name: REDIS_URI
          valueFrom:
            configMapKeyRef:
              key: REDIS_URI
              name: microserv.events-config-y2ek
        - name: SURREAL_URI
          valueFrom:
            configMapKeyRef:
              key: SURREAL_URI
              name: microserv.events-config-y2ek
        - name: SURREAL_USER
          valueFrom:
            configMapKeyRef:
              key: SURREAL_USER
              name: microserv.events-config-y2ek
        - name: SURREAL_PASS
          valueFrom:
            configMapKeyRef:
              key: SURREAL_PASS
              name: microserv.events-config-y2ek
        - name: MEDIA_MICROSERVICE_URL
          valueFrom:
            configMapKeyRef:
              key: MEDIA_MICROSERVICE_URL
              name: microserv.events-config-y2ek
        image: us-central1-docker.pkg.dev/partyscene-441317/scenes-backstage/microservices.events:latest
        imagePullPolicy: Always
        name: microservices-events-sha256-1
        resources:
          limits:
            ephemeral-storage: 1Gi
            memory: 1Gi
          requests:
            cpu: 250m
            ephemeral-storage: 1Gi
            memory: 512Mi
        securityContext:
          capabilities:
            drop:
            - NET_RAW
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: kubernetes.io/arch
        operator: Equal
        value: amd64
status:
  availableReplicas: 1
  collisionCount: 1
  conditions:
  - lastTransitionTime: "2025-04-14T20:31:34Z"
    lastUpdateTime: "2025-05-01T08:40:56Z"
    message: ReplicaSet "microserv.events-b76788589" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-05-01T08:47:11Z"
    lastUpdateTime: "2025-05-01T08:47:11Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 609
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
