apiVersion: v1
kind: Service
metadata:
  name: surreal-balancer
  labels:
    app: surrealdb
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  selector:
    app.kubernetes.io/instance: surrealdb-tikv  # <--- Add/Modify this line
    app.kubernetes.io/name: surrealdb      # <--- Add/Modify this line